version: '>=3.2'
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 0.0.0.0:9090:9090
    restart: always

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    hostname: monitoring
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netfs|rootfs/run/docker/aufs)($$|/)
    ports:
      - 127.0.0.1:9100:9100
    restart: always

  blackbox-exporter:
    image: prom/blackbox-exporter
    volumes:
      - ./blackbox:/config
    command:
      - --config.file=/config/blackbox.yml
    ports:
      - 127.0.0.1:9115:9115
    restart: always

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    volumes:
      - ./grafana/:/var/lib/grafana/
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - 0.0.0.0:3000:3000

  alertmanager:
    image: prom/alertmanager
    ports:
      - 0.0.0.0:9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    restart: always
    command:
      - --config.file=/etc/alertmanager/config.yml
      - --storage.path=/etc/alertmanager/data

